# Something’s Wrong!
# ----------------------------
  
# Indications that something’s not right
# -----------------------------------------
# message: A generic notification/diagnostic message produced by the 
# message function; execution of the function continues

# warning: An indication that something is wrong but not necessarily fatal; 
# execution of the function continues; generated by the warning function

# error: An indication that a fatal problem has occurred; execution stops; 
# produced by the stop function

# condition: A generic concept for indicating that something unexpected can 
# occur; programmers can create their own conditions

# Something’s Wrong!
# ---------------------

# Warning

log(-1)
# Output
# [1] NaN
# Warning message:
# In log(-1) : NaNs produced



printmessage <- function(x) 
  {
    if(x > 0)
      print("x is greater than zero")
    else
      print("x is less than or equal to zero")
  invisible(x)
  }


printmessage(NA)
# Output
# Error in if (x > 0) print("x is greater than zero") else 
#   print("x is less than or equal to zero") : 
#   missing value where TRUE/FALSE needed



printmessage2 <- function(x) 
  {
    if(is.na(x))
      print("x is a missing value!")
    else if(x > 0)
      print("x is greater than zero")
    else
      print("x is less than or equal to zero")
  invisible(x)
  }


printmessage2 <- function(x) 
  {
    if (is.na(x))
      print("x is a missing value!") else if (x > 0)
        print("x is greater than zero") else print("x is less than or equal to zero")
    invisible(x)
  }

x <- log(-1)
# Output
# Warning message:
#   In log(-1) : NaNs produced

printmessage2(x)
# [1] "x is a missing value!"


# Something’s Wrong!
  # 1. How do you know that something is wrong with your function?
  # 2. What was your input? How did you call the function?
  # 3. What were you expecting? Output, messages, other results?
  # 4. What did you get?
  # 5. How does what you get differ from what you were expecting?
  # 6. Were your expectations correct in the first place?
  # 7. Can you reproduce the problem (exactly)?